Add the Heroku app name to output.
niteoweb/reviewapps-deploy-status pull request #10
Opened 2020-03-19 09:21 UTC by mathieutu

Hi, 
As said in #9, you get the Heroku app name in the action and _convert_ it the the url. 

This PR adds the app name to the output, so developers can directly get it in their actions without extracting it from the url.

Thanks.

2020-03-26 14:53 UTC, mathieutu commented
Hey @suryasr007!
A litle up in case you didn't see that. 👋

2020-03-26 19:09 UTC, sayanarijit commented
Code looks good but need to test if it breaks the existing repos.

2020-03-26 19:18 UTC, mathieutu commented
Can't see how it could break anything, it just add a variable in the outputs. 🤔 

Moreover, the action is tagged, so if it breaks, it should not break the 1.3.0 version that existing repos use.

2020-03-26 19:48 UTC, sayanarijit commented
LGTM from me. Meanwhile, can you please `git rebase -i HEAD~3` into a single commit?

2020-03-26 19:50 UTC, sayanarijit commented
FYI you will need to force push after rebase.

2020-03-26 20:50 UTC, mathieutu commented
I can if you want (I actually didn't clone the repo, and made the changes directly in github), but if you click on "Stash and merge" button, I think it will do the exact same !

2020-03-26 21:10 UTC, zupo approved these changes

2020-03-27 02:34 UTC, suryasr007 approved these changes
I'll take it from here. Thanks, @sayanarijit and @zupo

2020-03-27 02:55 UTC, suryasr007 requested changes

2020-03-27 02:55 UTC, suryasr007 commented on action.yml
> +    description: "The name of the heroku review app deployed."
```suggestion
    description: "The name of the Heroku review app deployed."
```

2020-03-27 02:55 UTC, suryasr007 commented on action.yml
> +    description: "The URL to show the heroku review app deployed."
```suggestion
    description: "The URL of the Heroku review app deployed."
```

2020-03-27 02:55 UTC, suryasr007 commented on review_app_status.py
> +    print(f"::set-output name=review_app_name::{reviewapp_build_data['environment']}")
Follow the DRY (Don't repeat yourself) principle.
```python
reviewapp_name = reviewapp_build_data['environment'] # at https://github.com/niteoweb/reviewapps-deploy-status/pull/10/files#diff-3803057c7ddec8f39110437eb5f9b591R219

review_app_url = f"https://{reviewapp_name}.herokuapp.com"  # https://github.com/niteoweb/reviewapps-deploy-status/pull/10/files#diff-3803057c7ddec8f39110437eb5f9b591R220
```
```suggestion
    print(f"::set-output name=review_app_name::{reviewapp_name}")
```

2020-03-27 03:48 UTC, suryasr007 commented
Also make sure that code coverage is 100%. For reference: https://github.com/niteoweb/reviewapps-deploy-status/blob/master/tests.py#L311

2020-03-28 14:27 UTC, suryasr007 approved these changes
Everything is in order.

![image](https://user-images.githubusercontent.com/10533926/77825288-40ee1300-712e-11ea-802a-6f30ab1543f3.png)

Thanks for the Pull request

2020-03-28 14:28 UTC, merged